x_path: data/datasets/fe/preconv/xyz_train
y_path: data/datasets/fe/preconv/xanes_train

descriptor:
    type: wacsf
    params:
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

bootstrap: False
bootstrap_params: 
  n_boot: 3
  n_size: 1.0
  seed_boot: [97, 39, 22]

ensemble: False
ensemble_params:
  n_ens: 3
  weight_init_seed: [97, 39, 22]

data_params: False
augment:
  augment_type: random_noise
  # augment_type: random_combination
  augment_mult: 5
  # for random noise
  augment_params: 
    normal_mean: 0
    normal_sd: 0.1
  # for random combination
  # augment_params : {}

kfold: False
kfold_params:
  n_splits: 5
  n_repeats: 1
  loss: 
    loss_fn: mse 
    loss_args: null

lr_scheduler: 
  scheduler: True
  scheduler_type: step
  scheduler_param:
    step_size: 50
    gamma: 0.1

hyperparams: 
  model: cnn
  batch_size: 16
  out_channel: 32
  channel_mul: 2
  hidden_layer: 64
  activation: prelu
  loss:
    loss_fn: mse
    loss_args: null
  lr: 0.00001
  optim_fn: SGD
  dropout: 0.2
  weight_init_seed: 2023
  kernel_init: xavier_uniform
  bias_init: zeros
  kernel_size: 3
  stride: 1

seed: 2021
epochs: 1
variance_threshold: 0.0
model_eval : True