dataset:
  type: transformer
  root_path: data/graph-set/processed_train  # Path to save processed dataset
  xyz_path: data/graph-set/xyz_train         # Path to the directory containing .XYZ files
  xanes_path: data/graph-set/xanes_train     # Path to the directory containing XANES files
#  params:
#    preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
#    fourier: False
#    fourier_concat: False


descriptors:
  - type: mace
    params:
      invariants_only: True
      num_layers: 1
      absorber_atom_only: False

  - type: pdos

model:
  type: transformer
  params:
    hidden_size: 128
    dropout: 0.1
    n_heads: 8
    n_self_attn_layers: 2
    n_cross_attn_layers: 3

hyperparams:
  batch_size: 4
#  lr: 0.001
#  epochs: 100
#  optimizer: Adam
#  model_eval : False
#  seed: 2021
  loss: hybrid
#  loss_reg: None # L1 L2
#  loss_lambda: 0.0001

kfold: False
#kfold_params:
#  n_splits: 3
#  n_repeats: 1
#  seed: 2021

bootstrap: False
#bootstrap_params:
#  n_boot: 3
#  n_size: 1.0
#  weight_seed: [97, 39, 22]

ensemble: False
#ensemble_params:
#  n_ens: 3
#  weight_seed: [97, 39, 22]

lr_scheduler: False
#scheduler_params:
#  type: step
#  step_size: 10
#  gamma: 0.5


standardscaler: False