dataset:
  type: xanesx
  root_path: .github/workflows/data/fe
  xyz_path: .github/workflows/data/fe/xyz_train
  xanes_path: .github/workflows/data/fe/xanes_train
  params:
    fourier: False
    fourier_concat: False
    augment: False
    augment_params:
      type: random_noise #random_combination
      augment_mult: 5
      normal_mean: 0
      normal_sd: 0.1

descriptors:
  - type: wacsf
    params:
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

#LSTM
model:
   type: lstm
   params:
     hidden_size: 100
     hidden_out_size: 50
     num_layers: 1
     dropout: 0.2
     activation: prelu
   weights:
     kernel: xavier_uniform
     bias: zeros
     seed: 2025

hyperparams:
  batch_size: 3
  lr: 0.001
  epochs: 10
  optim_fn: Adam
  model_eval : False
  seed: 2021
  loss: mse
  loss_reg: L2 #None L1
  loss_lambda: 0.001

kfold: False
kfold_params:
  n_splits: 2
  n_repeats: 1
  seed: 2022

bootstrap: False
bootstrap_params:
  n_boot: 3
  n_size: 1.0
  weight_seed: [97, 39, 22]

ensemble: False
ensemble_params:
  n_ens: 3
  weight_seed: [97, 39, 22]

lr_scheduler: True
scheduler_params:
  type: step
  step_size: 1
  gamma: 0.5

data_augment: True
augment_params:
  type: random_noise
  augment_mult: 2
  normal_mean: 0
  normal_sd: 0.1
  # type: random_combination
  # augment_mult: 5

fourier_transform: False
fourier_params:
  concat: True

standardscaler: False