xyz_path:  .github/workflows/data/datasets/fe/preconv/xyz_train
xanes_path:  .github/workflows/data/datasets/fe/preconv/xanes_train

descriptor:
  - type: wacsf
    params:
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

#LSTM
model:
   type: lstm
   params:
     hidden_size: 100
     hidden_out_size: 50
     num_layers: 1
     dropout: 0.2
     activation: prelu

hyperparams:
  batch_size: 64
  lr: 0.00001
  epochs: 10
  optim_fn: Adam
  kernel_init: xavier_uniform
  bias_init: zeros
  model_eval : False
  seed: 2021
  weight_seed: 2023
  loss:
    loss_fn: mse
    loss_args: null
    loss_reg_type: L2 # null, L1, L2
    loss_reg_param: 0.001

kfold: False
kfold_params:
  n_splits: 5
  n_repeats: 1
  seed: 2022

lr_scheduler: True
scheduler_params:
  type: step
  step_size: 100
  gamma: 0.5

data_augment: False
augment_params:
  type: random_noise
  # augment_type: random_combination
  augment_mult: 5
  # for random noise
  normal_mean: 0
  normal_sd: 0.1
  # for random combination
  # augment_params : {}

bootstrap: False
bootstrap_params:
  n_boot: 3
  n_size: 1.0
  weight_seed: [97, 39, 22]

ensemble: False
ensemble_params:
  n_ens: 3
  weight_seed: [97, 39, 22]

optuna: False
optuna_params:
  n_trials: 3
  tune_optim_fn: True
  tune_batch_size: True
  tune_activation: True
  tune_loss_fn: True
  tune_lr: True
  tune_dropout: True
  tune_lstm: True

freeze: False
freeze_params:
  model_path: ./models/model_lstm_001
  n_lstm: 1
  n_dense: 2

fourier_transform: False
fourier_params:
  concat: True

standardscaler: False