dataset:
  root_path: .github/workflows/data/fe/processed_predict
  xyz_path:  .github/workflows/data/fe/xyz_test
  xanes_path:  .github/workflows/data/fe/xanes_test

plot_save: True
result_save: True

shap: False
shap_params:
  nsamples: 3
