# Example configuration for DimeNet++ training with toy data.

seed: 2025
device: cuda

datasource:
  datasource_type: pmgjson
  json_path: ./data/toy_data/
  spectrum_key: "XANES"

dataset: 
  # general:
  dataset_type: geometrygraph
  root: ./data/processed/toy_data_dimenet_pp/  # Where should the processed data be stored
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
  skip_prepare: False
  split_ratios: [0.8, 0.2]
  # params:
  graph_builder:
    graph_builder_type: cov_radius
    cutoff: 5.0
    cov_radii_scale: 2.5
    max_num_neighbors: 50
  compute_angles: True

encodings:
  - encoding_type: identity

model:
  # general:
  model_type: dimenet++
  # params:
  hidden_channels: 128
  out_channels: auto
  num_blocks: 6
  int_emb_size: 64
  basis_emb_size: 8
  out_emb_channels: 256
  num_spherical: 7
  num_radial: 6
  cutoff: 5.0
  envelope_exponent: 5
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  act: swish
  output_initializer: glorot_orthogonal

trainer:
  # general:
  trainer_type: basic
  batch_size: 4
  shuffle: True
  drop_last: False
  num_workers: 0
  # params:
  epochs: 50
  learning_rate: 0.001
  optimizer: Adam
  max_norm: null
  validation_interval: 10
  lr_warmup: True
  warmup_steps: 500
  loss:
    - loss_type: mse
  regularizer:
    regularizer_type: none
  lr_scheduler:
    lr_scheduler_type: linear
    start_factor: 1.0 
    end_factor: 0.1
    total_iters: 40
  early_stopper:
    early_stopper_type: basic 
    patience: 25
    min_delta: 0.001
    restore_best: True
  
strategy:
  # general:
  strategy_type: single
  weight_init: xavier_uniform
  bias_init: zeros
  checkpoint_interval: 25
  # params: