# Example configuration for GemNet training with toy data.

seed: 2025
device: cuda

datasource:
  datasource_type: pmgjson
  json_path: ./data/toy_data/

dataset:
  # general:
  dataset_type: gemnet
  root: ./data/processed/toy_data_gemnet/  # Where should the processed data be stored
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
  skip_prepare: False
  split_ratios: [0.8, 0.2]
  # params:
  graph_builder:
    graph_builder_type: cov_radius
    cutoff: 5.0
    cov_radii_scale: 2.5
    max_num_neighbors: 50
  # Quadruplets:
  quadruplets: True
  int_graph_builder:
    graph_builder_type: cov_radius
    cutoff: 5.0
    cov_radii_scale: 3.5
    max_num_neighbors: 50
  # OC-specific params (ignored for non-OC gemnet):
  oc_mode: False
  oc_aeaint_graph_builder: null
  oc_aint_graph_builder: null

encodings:
  - encoding_type: identity

model:
  # general:
  model_type: gemnet
  # params:
  num_targets: auto
  num_spherical: 7
  num_radial: 6
  num_blocks: 4
  emb_size_atom: 128
  emb_size_edge: 128
  emb_size_trip: 64
  emb_size_quad: 32
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  emb_size_bil_quad: 32
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  triplets_only: True
  cutoff: 5.0
  int_cutoff: 10.0
  envelope_exponent: 5
  output_init: HeOrthogonal
  activation: swish
  num_elements: 100

trainer:
  # general:
  trainer_type: basic
  batch_size: 4
  shuffle: True
  drop_last: False
  num_workers: 0
  # params:
  epochs: 50
  learning_rate: 0.001
  optimizer: Adam
  max_norm: null
  validation_interval: 10
  lr_warmup: True
  warmup_steps: 500
  loss:
    - loss_type: mse
  regularizer:
    regularizer_type: none
  lr_scheduler:
    lr_scheduler_type: linear
    start_factor: 1.0 
    end_factor: 0.1
    total_iters: 40
  early_stopper:
    early_stopper_type: basic 
    patience: 25
    min_delta: 0.001
    restore_best: True
  
strategy:
  # general:
  strategy_type: single
  weight_init: xavier_uniform
  bias_init: zeros
  checkpoint_interval: 25
  # params:
  checkpoint_interval: 25
  # params:
