seed: 2025
device: cuda

datasource:
  datasource_type: pmgjson
  json_path: /media/hendrik/ExternalSSD/final_data/omnixas_test/

dataset:
  # general:
  dataset_type: gemnet
  root: ./data/omnixas/processed_train_gemnet/  # Where should the processed data be stored
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
  skip_prepare: True
  split_ratios: null
  split_indexfile: ./data/scales/split_indices_gemnet.json
  # params:
  cutoff: 5.0
  max_num_neighbors: 32
  graph_method: voronoi
  min_facet_area: 5.0%
  cov_radii_scale: 1.5
  # Quadruplets:
  quadruplets: True
  int_cutoff: 10.0
  int_max_neighbors: 50
  int_graph_method: radius
  int_min_facet_area: null
  int_cov_radii_scale: null
  # OC-specific params (ignored for non-OC gemnet):
  oc_mode: False
  oc_cutoff_aeaint: null
  oc_max_neighbors_aeaint: null
  oc_graph_method_aeaint: null
  oc_min_facet_area_aeaint: null
  oc_cov_radii_scale_aeaint: null
  oc_cutoff_aint: null
  oc_max_neighbors_aint: null
  oc_graph_method_aint: null
  oc_min_facet_area_aint: null
  oc_cov_radii_scale_aint: null

encodings:
  - encoding_type: identity

model:
  # general:
  model_type: gemnet
  # params:
  num_targets: auto
  num_spherical: 7
  num_radial: 6
  num_blocks: 4
  emb_size_atom: 128
  emb_size_edge: 128
  emb_size_trip: 64
  emb_size_quad: 32
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  emb_size_bil_quad: 32
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  triplets_only: True
  cutoff: 5.0
  int_cutoff: 10.0
  envelope_exponent: 5
  output_init: HeOrthogonal
  activation: swish
  scale_file: ./data/scales/scales_gemnet.json
  num_elements: 100

trainer:
  # general:
  trainer_type: basic
  batch_size: 16
  shuffle: True
  drop_last: False
  num_workers: 0
  # params:
  epochs: 500
  learning_rate: 0.001
  optimizer: Adam
  max_norm: null
  validation_interval: 10
  lr_warmup: True
  warmup_steps: 500
  loss:
    - loss_type: mse
  regularizer:
    regularizer_type: none
  lr_scheduler:
    lr_scheduler_type: linear
    start_factor: 1.0 
    end_factor: 0.1
    total_iters: 40
  early_stopper:
    early_stopper_type: basic 
    patience: 25
    min_delta: 0.001
    restore_best: True
  
strategy:
  # general:
  strategy_type: single
  weight_init: xavier_uniform
  weight_init_params: {}
  bias_init: zeros
  checkpoint_interval: 25
  # params:
