# NOT FULLY TESTED - STILL WORK IN PROGRESS

seed: 2025
device: cuda

datasource:
  datasource_type: xyzspec
  xyz_path: ./data/fe/xyz_test
  xanes_path: ./data/fe/xanes_test

dataset:
  root: ./data/fe/processed_test/ # Where should the processed data be stored
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly

inferencer:
  inferencer_type: basic
  batch_size: 3
  shuffle: False
  drop_last: False
  num_workers: 0
  buffer_size: 100000