# Example configuration for multi-head CNN training with toy data.

seed: 2025
device: cpu

datasource:
  datasource_type: multipmgjson
  root_path: ./data/toy_data_multipmgjson
  spectrum_key: "XANES"

dataset:
  # general:
  dataset_type: multihead
  root: ./data/processed/toy_data_cnn/  # Where should the processed data be stored
  preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
  skip_prepare: False
  split_ratios: [0.8, 0.2]
  # params:
  # descriptors:
  descriptors:
    - descriptor_type: wacsf
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

encodings:
  - encoding_type: identity

model:
  # general:
  model_type: mh_cnn
  # params:
  in_size: auto
  out_size: auto
  hidden_size: 512
  dropout: 0.1
  num_conv_layers: 3
  activation: prelu
  out_channel: 32
  channel_mul: 2
  kernel_size: 3
  stride: 2
  head_hidden_size: 512
  head_num_hidden_layers: 2
  head_shrink_rate: 1.0

trainer:
  # general:
  trainer_type: basic
  batch_size: 5
  shuffle: True
  drop_last: True
  num_workers: 0
  # params:
  epochs: 50
  learning_rate: 0.001
  optimizer: Adam
  max_norm: null
  validation_interval: 10
  lr_warmup: True
  warmup_steps: 500
  loss:
    - loss_type: mse
  regularizer:
    regularizer_type: none
  lr_scheduler:
    lr_scheduler_type: linear
    start_factor: 1.0
    end_factor: 0.1
    total_iters: 40
  early_stopper:
    early_stopper_type: basic
    patience: 25
    min_delta: 0.001
    restore_best: True

strategy:
  # general:
  strategy_type: single
  weight_init: xavier_uniform
  bias_init: zeros
  checkpoint_interval: 25
  # params:
