# Example configuration for SchNet training with toy data.

seed: 2025
device: cuda

datasource:
  datasource_type: pmgjson
  json_path: ./data/toy_data/


dataset: 
  # general:
  dataset_type: geometrygraph
  root: ./data/processed/toy_data_schnet/  # Where should the processed data be stored
  preload: True                           # Preload dataset into RAM if True; otherwise load on-the-fly
  skip_prepare: False
  split_ratios: [0.8, 0.2]
  # params:
  graph_builder:
    graph_builder_type: cov_radius
    cutoff: 5.0
    cov_radii_scale: 2.5
    max_num_neighbors: 50

encodings:
  - encoding_type: identity

model:
  # general:
  model_type: schnet
  # params:
  hidden_channels: 128
  reduce_channels_1: 64
  reduce_channels_2: auto
  num_filters: 128
  num_interactions: 6
  num_gaussians: 50
  cutoff: 5.0

trainer:
  # general:
  trainer_type: basic
  batch_size: 4
  shuffle: True
  drop_last: False
  num_workers: 0
  # params:
  epochs: 500
  learning_rate: 0.001
  optimizer: Adam
  max_norm: null
  validation_interval: 10
  lr_warmup: True
  warmup_steps: 500
  loss:
    - loss_type: mse
  regularizer:
    regularizer_type: none
  lr_scheduler:
    lr_scheduler_type: linear
    start_factor: 1.0 
    end_factor: 0.1
    total_iters: 40
  early_stopper:
    early_stopper_type: basic 
    patience: 25
    min_delta: 0.001
    restore_best: True
  
strategy:
  # general:
  strategy_type: single
  weight_init: xavier_uniform
  bias_init: zeros
  checkpoint_interval: 25
  # params: