name: Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: MLP XYZ --> Xanes
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xyz --inp_f ./.github/workflows/inputs/in_mlp.yaml
          # python3 -m xanesnet.cli --mode predict_xanes --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml


      - name: MLP Xanes --> XYZ
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xanes --inp_f ./.github/workflows/inputs/in_mlp.yaml
          # python3 -m xanesnet.cli --mode predict_xyz --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml
          
      - name: CNN XYZ --> Xanes
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xyz --inp_f ./.github/workflows/inputs/in_cnn.yaml
          # python3 -m xanesnet.cli --mode predict_xanes --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: LSTM XYZ --> Xanes
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xyz --inp_f ./.github/workflows/inputs/in_lstm.yaml
          # python3 -m xanesnet.cli --mode predict_xanes --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: LSTM XANES --> XYZ
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xanes --inp_f ./.github/workflows/inputs/in_lstm.yaml
          # python3 -m xanesnet.cli --mode predict_xyz --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: CNN Xanes --> XYZ
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xanes --inp_f ./.github/workflows/inputs/in_cnn.yaml
          # python3 -m xanesnet.cli --mode predict_xyz --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: AE_MLP XYZ -> Xanes
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xyz --inp_f ./.github/workflows/inputs/in_ae_mlp.yaml
          # python3 -m xanesnet.cli --mode predict_xanes --model_mode ae_mlp --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: AE_MLP Xanes --> XYZ
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xanes --inp_f ./.github/workflows/inputs/in_ae_mlp.yaml
          # python3 -m xanesnet.cli --mode predict_xyz  --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: AE_CNN XYZ --> Xanes
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xyz --inp_f ./.github/workflows/inputs/in_ae_cnn.yaml
          # python3 -m xanesnet.cli --mode predict_xanes --mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: AE_CNN Xanes --> XYZ
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_xanes --inp_f ./.github/workflows/inputs/in_ae_cnn.yaml
          # python3 -m xanesnet.cli --mode predict_xyz ---mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml

      - name: AEGAN
        run: |
          rm -rf model/model_001
          python3 -m xanesnet.cli --mode train_aegan --inp_f ./.github/workflows/inputs/in_aegan.yaml
          # python3 -m xanesnet.cli --mode predict_all ---mdl model/model_001 --inp_f ./.github/workflows/inputs/in_predict.yaml



