name: docs

on:
  push:
    branches:
      - '*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
      - name: Sphinx Build
        working-directory: ./docs
        run: | 
          make html
          touch build/html/.nojekyll
      - name: Deploy to GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/build/html
          target-folder: docs
          clean: true
